export const adminHtml = `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>足跡防護｜測試統計</title><style>
body{font:16px/1.6 system-ui,sans-serif;background:#142131;color:#e9f2f5;margin:0}main{max-width:1060px;margin:auto;padding:24px}h1,h2{line-height:1.3}button{font:inherit;background:#f4d15a;color:#142131;border:0;padding:9px 13px;border-radius:6px;cursor:pointer;margin:4px}section{background:#20354a;margin:18px 0;padding:18px;border-radius:8px}table{border-collapse:collapse;width:100%;margin:10px 0}th,td{border-bottom:1px solid #527087;text-align:left;padding:7px;vertical-align:top}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px}.card{border:1px solid #56738c;border-radius:7px;padding:12px}.scroll{overflow:auto}label{display:block;margin:10px 0}input{font:inherit;padding:5px}#error{color:#ffb19d}
</style></head><body><main><h1>足跡防護測試統計</h1><p>所有受測者使用相同八題；這裡是單次作答統計，不能當成前後測進步。小樣本只作描述。</p><button id="refresh">重新整理</button><button id="csv">匯出匿名 CSV</button><p id="error" role="alert"></p><div id="content">讀取中…</div><section><h2>刪除測試資料</h2><p>刪除後主資料無法由此頁復原。</p><label>刪除指定日期以前的紀錄（UTC，不含當日） <input type="date" id="before"></label><button id="deleteOld">刪除指定日期以前</button><button id="deleteAll">刪除全部紀錄</button></section></main><script type="module">
const $=id=>document.getElementById(id);const fmt=x=>x==null?'尚無資料':String(x);const ratio=x=>x.denominator?x.count+' / '+x.denominator+'（'+x.percent+'%）':'尚無資料（0 / 0）';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const line=(name,value)=>'<div class="card"><strong>'+esc(name)+'</strong><br>'+ratio(value)+'</div>';
const table=(headers,rows)=>rows.length?'<div class="scroll"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<p>尚無資料</p>';
async function refresh(){try{const response=await fetch('./api/admin/stats',{cache:'no-store'});if(!response.ok)throw Error('無法讀取統計（'+response.status+'），請先登入管理者帳號。');const s=await response.json();$('error').textContent='';$('content').innerHTML=
'<section><h2>參與情況</h2><div class="grid">'+line('同意並開始',s.participation.started)+line('完成八題與回查',s.participation.completed)+line('中途退出',s.participation.dropout)+'</div></section>'+
'<section><h2>單次作答表現</h2><p>完成者 '+s.score.denominator+' 人；平均總分 '+fmt(s.score.average)+' / 100；辨識 '+fmt(s.score.recognitionAverage)+' / 40；防護 '+fmt(s.score.protectionAverage)+' / 40；回查 '+fmt(s.score.reviewAverage)+' / 20。這些分數不能表示測試前後的改變。</p>'+table(['分數範圍','人數 / 分母 / %'],s.score.distribution.map(r=>[r.label,ratio(r)]))+'<h3>三階段答對率</h3>'+table(['階段','答對題數 / 作答題數 / %'],s.stages.map(r=>[['辨識','防護','回查'][r.stage],ratio(r)]))+'</section>'+
'<section><h2>各題與完成時間</h2><p>完整流程時間中位數：'+fmt(s.durationMedianMinutes)+' 分鐘（僅完成者）。</p>'+table(['題庫版本','題目','階段','答對率','常見錯誤選項（人數 / 分母 / %）'],s.items.map(r=>[r.version,r.id,['辨識','防護','回查'][r.stage],ratio(r.correct),r.wrong.map(w=>w.id+': '+ratio(w)).join('；')||'尚無資料']))+'</section>';
}catch(error){$('error').textContent=error.message;}}
$('refresh').onclick=refresh;$('csv').onclick=()=>location.href='./api/admin/export';
async function remove(all){const before=$('before').value;if(!all&&!/^\\d{4}-\\d{2}-\\d{2}$/.test(before)){alert('請選日期');return;}if(!confirm(all?'刪除所有測試資料？':'刪除 '+before+' 以前的測試資料？')||prompt('請輸入「刪除」確認')!=='刪除')return;try{const response=await fetch('./api/admin/sessions',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify(all?{all:true}:{before})});if(!response.ok)throw Error('刪除失敗（'+response.status+'）');await refresh();}catch(error){$('error').textContent=error.message;}}
$('deleteOld').onclick=()=>remove(false);$('deleteAll').onclick=()=>remove(true);refresh();
</script></body></html>`;
