export const adminHtml = `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>足跡防護｜研究統計</title><style>
body{font:16px/1.6 system-ui,sans-serif;background:#142131;color:#e9f2f5;margin:0}main{max-width:1060px;margin:auto;padding:24px}h1,h2{line-height:1.3}button,a{font:inherit;background:#f4d15a;color:#142131;border:0;padding:9px 13px;border-radius:6px;cursor:pointer;margin:4px}section{background:#20354a;margin:18px 0;padding:18px;border-radius:8px}table{border-collapse:collapse;width:100%;margin:10px 0}th,td{border-bottom:1px solid #527087;text-align:left;padding:7px;vertical-align:top}small,.muted{color:#becbd8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:10px}.card{border:1px solid #56738c;border-radius:7px;padding:12px}.scroll{overflow:auto}label{display:block;margin:10px 0}input{font:inherit;padding:5px}#error{color:#ffb19d}
</style></head><body><main><h1>研究測試統計</h1><p>只顯示正式資料庫目前資料；小樣本請勿推論到所有人。協助程度為受測者自填。</p><button id="refresh">重新整理</button><button id="csv">匯出匿名 CSV</button><p id="error" role="alert"></p><div id="content">讀取中…</div><section><h2>刪除測試資料</h2><p>請確認保存期限與學校規定。刪除後不可由此頁復原。</p><label>刪除指定日期以前的紀錄（UTC，不含當日） <input type="date" id="before"></label><button id="deleteOld">刪除指定日期以前</button><button id="deleteAll">刪除全部紀錄</button></section></main><script type="module">
const $=id=>document.getElementById(id); const fmt=x=>x==null?'尚無資料':String(x);const ratio=x=>x.denominator?x.count+' / '+x.denominator+'（'+x.percent+'%）':'尚無資料（0 / 0）';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={identity:'身分',location:'位置',time:'時間',link:'跨平台關聯',protection:'防護',instructions:'說明',wording:'用詞',navigation:'操作',display:'畫面',connection:'網路',other:'其他',none:'無'};
const line=(name,value)=>'<div class="card"><strong>'+esc(name)+'</strong><br>'+ratio(value)+'</div>';
const table=(headers,rows)=>rows.length?'<div class="scroll"><table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<p>尚無資料</p>';
async function refresh(){try{const res=await fetch('./api/admin/stats',{cache:'no-store'});if(!res.ok)throw Error('無法讀取統計（'+res.status+'），請先登入管理者帳號。');const s=await res.json();$('error').textContent='';$('content').innerHTML=
'<section><h2>參與與流失</h2><div class="grid">'+Object.entries({同意並開始:s.participation.started,完成前測:s.participation.pre,完成原網站流程:s.participation.experience,完成後測:s.participation.post,完成整個流程:s.participation.complete,配對前後測:s.participation.paired,前測前流失:s.participation.dropout.beforePre,原網站流程流失:s.participation.dropout.duringExperience,後測前流失:s.participation.dropout.beforePost,問卷前流失:s.participation.dropout.beforeSurvey}).map(([k,v])=>line(k,v)).join('')+'</div></section>'+
'<section><h2>辨識能力（僅配對樣本）</h2><p>前測平均 '+fmt(s.ability.preAverage)+' / 100；後測平均 '+fmt(s.ability.postAverage)+' / 100；平均差 '+fmt(s.ability.gainPoints)+' 百分點（目標 ≥20 百分點）。分母 '+s.pairedCount+' 人。</p>'+table(['得分','前測人數 / 分母 / %','後測人數 / 分母 / %'],s.ability.preDistribution.map((r,i)=>[r.value,ratio(r),ratio(s.ability.postDistribution[i])]))+table(['線索','前測答對','後測答對'],s.ability.categories.map(r=>[names[r.category],ratio(r.pre),ratio(r.post)]))+'</section>'+
'<section><h2>提案指標</h2><div class="grid">'+line('防護判斷（目標 ≥80%）',s.protection)+line('行動意願（目標 ≥70%，非實際行為）',s.actionIntention)+line('操作理解（目標 ≥80%，自填協助程度）',s.operationUnderstanding)+'</div></section>'+
'<section><h2>補充資料</h2><p>A→B '+ratio(s.groups.AB)+'；B→A '+ratio(s.groups.BA)+'；完整流程時間中位數 '+fmt(s.durationMedianMinutes)+' 分鐘。</p><h3>易用性評價（1 低至 5 高）</h3>'+table(['評價','人數 / 分母 / %'],s.ease.map(r=>[r.value,ratio(r)]))+'<h3>問題類型（可複選）</h3>'+table(['類型','人數 / 分母 / %'],s.problems.map(r=>[names[r.id],ratio(r)]))+'<h3>各題答對率與常見錯誤選項</h3>'+table(['階段','題庫 / 版本','題目','線索','答對','錯誤選項（人數 / 分母 / %）'],s.items.map(r=>[r.stage==='pre'?'前測':'後測',r.bank+' / '+r.version,r.id,names[r.category],ratio(r.correct),r.wrong.map(w=>w.id+': '+ratio(w)).join('；')||'尚無資料']))+'</section>';
}catch(e){$('error').textContent=e.message;}}
$('refresh').onclick=refresh;$('csv').onclick=()=>location.href='./api/admin/export';
async function remove(all){const before=$('before').value;if(!all&&!/^\\d{4}-\\d{2}-\\d{2}$/.test(before)){alert('請選日期');return;}const message=all?'刪除所有研究資料？':'刪除 '+before+' 以前的研究資料？';if(!confirm(message)||prompt('請輸入「刪除」確認')!=='刪除')return;try{const res=await fetch('./api/admin/sessions',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify(all?{all:true}:{before})});if(!res.ok)throw Error('刪除失敗（'+res.status+'）');await refresh();}catch(e){$('error').textContent=e.message;}}
$('deleteOld').onclick=()=>remove(false);$('deleteAll').onclick=()=>remove(true);refresh();
</script></body></html>`;
