export const studyAdminHtml=String.raw`<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>足跡防護｜複賽研究後台</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{font:16px/1.65 system-ui,sans-serif;background:#101c2b;color:#e9f2f5;margin:0}main{max-width:1180px;margin:auto;padding:28px 20px}h1{font-size:30px}h2{font-size:23px}h3{font-size:18px}section{background:#1b2d41;margin:22px 0;padding:24px;border:1px solid #3b536b;border-radius:12px}p,small{color:#bacbda}.toolbar{display:flex;gap:10px;flex-wrap:wrap}button,a.button{font:inherit;background:#f4d15a;color:#142131;border:0;padding:9px 15px;border-radius:6px;cursor:pointer;text-decoration:none}button.secondary,a.button{background:#2e445c;color:#e9f2f5}button:disabled{opacity:.45;cursor:wait}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #445c75;vertical-align:top}th{color:#c2d0de}.scroll{overflow:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.bar-row{margin:13px 0}.bar-label{display:flex;justify-content:space-between;gap:12px}.bar{height:14px;background:#314962;border-radius:4px;overflow:hidden;margin-top:5px}.bar span{display:block;height:100%;background:#8cd9d7}.bar.post span{background:#f4d15a}.note{border-left:3px solid #f4d15a;background:#243c50;padding:16px}.score{font-size:24px;color:#f4d15a}label{display:block;margin:12px 0}input,select,textarea{font:inherit;background:#101c2b;color:#e9f2f5;border:1px solid #70859a;padding:9px;border-radius:5px;max-width:100%}textarea{display:block;width:100%;min-height:95px}#report{min-height:350px;white-space:pre-wrap}#error{color:#ffb19d}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:12px;background:#101c2b}.feedback-row{border:1px solid #516a81;padding:12px;margin:12px 0}.success{color:#9be5c4}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible{outline:3px solid #8dd7eb;outline-offset:3px}[hidden]{display:none!important}@media(max-width:600px){main{padding:16px 12px}section{padding:16px}.bar-label{display:block}h1{font-size:26px}}
</style></head><body><main><header><small>FOOTPRINT / PAIRED STUDY</small><h1>足跡防護複賽研究後台</h1><p>四項成效指標僅使用新研究資料。舊八題紀錄保留，未混入前後測。</p></header><div class="toolbar"><button id="refresh">重新整理</button><button id="copy" disabled>複製簡報整理資料</button><button id="preview" class="secondary" disabled>預覽內容</button><button id="txt" class="secondary" disabled>下載為TXT</button><button id="csv" class="secondary" disabled>匯出研究CSV</button><a class="button" href="/admin/legacy">查看舊八題資料</a><a class="button" href="/cdn-cgi/access/logout">登出</a></div><p id="status" role="status">讀取中…</p><p id="error" role="alert"></p><section id="report-panel" hidden><h2>簡報整理文字</h2><p>若自動複製失敗，請在下方文字框全選後複製。此內容不含受測者編號、管理帳號或原始自由填答。</p><textarea id="report" readonly aria-label="可手動複製的簡報整理資料"></textarea></section><div id="content" aria-live="polite"></div><section><h2>管理者補充欄位</h2><p>先去除姓名、學校名稱、帳號及聯絡資料再填寫。回饋請自行改寫，系統不會直接帶入原始自由填答。自動遮罩不能完整辨認所有姓名，仍須管理者檢查。</p><form id="metadata"><div class="grid"><label>測試日期<textarea name="testingDate" maxlength="800"></textarea></label><label>測試地點或方式（避免精確地點）<textarea name="method" maxlength="800"></textarea></label><label>測試對象來源（如同齡自願參與者，不填校名）<textarea name="source" maxlength="800"></textarea></label><label>是否有對照組<select name="controlGroup"><option value="unknown">尚無資料</option><option value="no">無</option><option value="yes">有，請補充設計</option></select></label><label>測試限制<textarea name="limitations" maxlength="800"></textarea></label><label>測試後發現<textarea name="finding" maxlength="800"></textarea></label><label>對應數據或回饋<textarea name="evidence" maxlength="800"></textarea></label><label>已完成的網站修改<textarea name="completedChanges" maxlength="800"></textarea></label><label>預計進行的修改<textarea name="plannedChanges" maxlength="800"></textarea></label></div><h3>可放入簡報的匿名回饋</h3><div id="feedback-edit"></div><button type="button" id="add-feedback" class="secondary">新增已去除個資的回饋</button><label><input type="checkbox" name="privacyReviewed">我已逐欄去除姓名、學校、帳號及其他辨識資訊；允許將這些補充文字加入簡報資料。</label><button id="save" disabled>儲存補充欄位</button><p id="save-status" role="status"></p></form></section><section><h2>原始選填回饋（僅供管理者審閱）</h2><p>可能含個資，不會自動複製或匯出；不要原文貼到公開簡報。請在補充欄位重新寫成不含個資的摘要，勾選後才加入。</p><div id="raw-feedback"></div></section><section><h2>依受測者要求刪除單筆研究紀錄</h2><p>先完成私下備份。此功能只刪除你指定的匿名編號及其前後測／問卷，不會刪除舊八題資料。刪除無法從本頁復原。</p><label>受測者提供的匿名編號<input id="delete-id" type="text" maxlength="36"></label><button id="delete-one" class="secondary" disabled>刪除指定研究紀錄</button><p id="delete-status" role="status"></p></section></main><script type="module">
const $=id=>document.getElementById(id);let latest=null,busy=false,dirty=false;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>x==null?'尚無資料':String(x);
const ratio=(m,unit='人')=>m.denominator?m.percent+'%（'+m.count+'/'+m.denominator+unit+'）':'尚無資料（0/0'+unit+'）';
const goal=m=>m.met==null?'尚無資料':(m.met?'達成':'未達成')+' '+m.threshold+'% 目標';
const bar=(label,m,post=false,unit='人')=>'<div class="bar-row"><div class="bar-label"><span>'+esc(label)+'</span><span>'+esc(ratio(m,unit))+'</span></div>'+(m.denominator?'<div class="bar '+(post?'post':'')+'" role="img" aria-label="'+esc(label+' '+ratio(m,unit))+'"><span style="width:'+Math.max(0,Math.min(100,m.percent))+'%"></span></div>':'')+'</div>';
const table=(headers,rows)=>rows.length?'<div class="scroll"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>':'<p>尚無資料</p>';
function lock(ready){for(const id of ['copy','preview','txt','csv','save','delete-one'])$(id).disabled=!ready;}
function feedbackRow(value={text:'',approved:false}){const div=document.createElement('div');div.className='feedback-row';div.innerHTML='<label>已去除個資的回饋<textarea maxlength="400" class="feedback-text"></textarea></label><label><input class="feedback-approved" type="checkbox">勾選：此段可加入簡報</label>';div.querySelector('textarea').value=value.text;div.querySelector('input').checked=value.approved;$('feedback-edit').append(div);}
function fillMetadata(m){const form=$('metadata');for(const key of ['testingDate','method','source','controlGroup','limitations','finding','evidence','completedChanges','plannedChanges'])form.elements.namedItem(key).value=m[key];form.elements.namedItem('privacyReviewed').checked=m.privacyReviewed;$('feedback-edit').replaceChildren();for(const f of m.feedback)feedbackRow(f);}
function render(s){const p=s.participation,r=s.recognition;
 $('content').innerHTML='<p class="note">'+(s.meta.enabled?'研究入口已開放。':'A/B題庫草稿尚未正式開放；一般體驗與舊資料保留。')+' 題庫 '+esc(s.meta.version)+'；網站 '+esc(s.meta.websiteVersion)+'。主資料保存 '+s.meta.retentionDays+' 天。</p>'+
 '<section><h2>測試流程漏斗圖</h2>'+bar('同意並開始',p.started)+bar('完成前測',p.pre)+bar('完成網站體驗',p.learning)+bar('完成後測',p.post)+bar('有效前後測配對',p.paired)+bar('整體完成（含問卷）',p.completed)+'<p>以上分母均為所有開始者。各階段尚未完成包含正在作答及可能退出者。</p>'+table(['階段','本階段尚未完成／進入該階段'],p.dropouts.map(d=>[d.stage,ratio(d)]))+table(['順序','開始分布','有效配對分布'],s.orders.map(o=>[o.order==='AB'?'A→B':'B→A',ratio(o.started),ratio(o.paired)]))+'<p>完成時間中位數：'+fmt(s.duration.medianMinutes)+' 分鐘（完成者 '+s.duration.denominator+' 人）。版本或答案無效而未納入配對：'+s.invalidPairs+' 人。</p></section>'+
 '<section><h2>前測與後測平均答對率</h2>'+bar('前測',r.pre,false,'題')+bar('後測',r.post,true,'題')+'<p>答對題數的分母為有效配對 '+p.paired.count+' 人 × 4題，先逐人換算0–100分後取平均。</p><p class="score">平均提升 '+fmt(r.meanChange)+(r.meanChange===null?'':' 百分點')+'</p><p>'+(r.met===null?'尚無資料':r.met?'達成':'未達成')+'平均提升20個百分點目標。</p>'+table(['變化','人數／有效配對'],[['進步',ratio(r.improved)],['持平',ratio(r.steady)],['退步',ratio(r.declined)]])+table(['分數','前測分布','後測分布'],r.distribution.map(d=>[d.score,ratio(d.pre),ratio(d.post)]))+'</section>'+
 '<section><h2>四類線索前後測比較圖</h2><div class="grid">'+r.categories.map(c=>'<div><h3>'+esc(c.label)+'</h3>'+bar('前測',c.pre)+bar('後測',c.post,true)+'<p>提升 '+fmt(c.change)+(c.change===null?'':' 百分點')+'；樣本 '+c.pre.denominator+' 人。</p></div>').join('')+'</div></section>'+
 '<section><h2>每位匿名受測者的前後測變化圖</h2><p>下列標籤只供本次統計顯示，不放入簡報複製文字。</p>'+ (s.changes.length?s.changes.map(c=>'<div class="bar-row"><strong>'+esc(c.label)+'</strong><div class="bar" role="img" aria-label="前測 '+c.pre+'分"><span style="width:'+c.pre+'%"></span></div><div class="bar post" role="img" aria-label="後測 '+c.post+'分"><span style="width:'+c.post+'%"></span></div><small>前 '+c.pre+'分 → 後 '+c.post+'分；變化 '+c.change+' 百分點（滿分100分；各1人）</small></div>').join(''):'<p>尚無資料</p>')+'</section>'+
 '<section><h2>防護判斷達標比例</h2>'+bar('至少兩項適當方法且沒有錯誤方法',s.protection,true)+'<p>'+goal(s.protection)+'。分母為有效前後測配對者，與學習八題分數無關。</p></section>'+
 '<section><h2>行動意願選項分布</h2>'+bar('至少一項具體行動／有效配對',s.actionIntent,true)+'<p>'+goal(s.actionIntent)+'。此為行動意願，不能視為實際行為改變；未填問卷的配對者仍保留在核心指標分母。</p>'+s.survey.actions.map(a=>bar(a.text,a)).join('')+'<p>各選項分母為完成問卷 '+s.survey.answered+' 人，多選可超過100%。暫不採取行動與其他項目互斥。</p></section>'+
 '<section><h2>協助程度分布與操作理解</h2>'+bar('完整完成且不需／少量協助',s.operation,true)+'<p>'+goal(s.operation)+'。分母含所有開始者，協助程度由受測者自填。未完成者不列入分子。</p>'+s.survey.assistance.map(a=>bar(a.text,a)).join('')+table(['完整完成者的協助程度','人數／全部開始者'],s.survey.completedAssistance.map(a=>[a.text,ratio(a)]))+'</section>'+
 '<section><h2>最常答錯題目排行</h2>'+(s.worst.length?s.worst.map(i=>bar((i.phase==='pre'?'前測':'後測')+' '+i.id+' 答錯',{count:i.correct.denominator-i.correct.count,denominator:i.correct.denominator,percent:Math.round((1-i.correct.count/i.correct.denominator)*1000)/10})).join(''):'<p>尚無資料</p>')+'</section>'+
 '<section><h2>各題與各選項統計</h2>'+table(['階段／題庫版本','題目','答對率','各選項選擇次數'],s.items.map(i=>[(i.phase==='pre'?'前測':'後測')+' '+i.version,i.id+' '+i.prompt,ratio(i.correct),i.options.map(o=>o.text+'：'+ratio(o)+(o.appropriate?'（正確／適當）':'（錯誤／不適當）')).join('；')]))+'</section>'+
 '<section><h2>網站易用性與操作問題</h2><p>易用性平均：'+fmt(s.survey.usabilityAverage)+'（問卷 '+s.survey.answered+' 人；1最難懂，5最易懂）</p>'+s.survey.usability.map(u=>bar(u.score+'分',u)).join('')+s.survey.problems.map(o=>bar(o.text,o)).join('')+'</section>';
 if(!dirty)fillMetadata(s.metadata.content);$('raw-feedback').innerHTML=s.rawFeedback.length?s.rawFeedback.map(f=>'<pre>'+esc(f.text)+'</pre>').join(''):'<p>未提供</p>';
 $('status').textContent='資料更新：'+new Date(s.meta.updatedAt).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})+'（臺北時間）';
}
async function refresh(){if(busy)return null;busy=true;lock(false);$('refresh').disabled=true;try{const response=await fetch('/api/admin/study/stats',{cache:'no-store',redirect:'error'});if(!response.ok)throw Error('無法讀取最新統計，請重新登入（'+response.status+'）。');latest=await response.json();render(latest);$('error').textContent='';lock(true);return latest;}catch(e){latest=null;lock(false);$('content').textContent='目前無法顯示統計。';$('raw-feedback').replaceChildren();$('report').value='';$('report-panel').hidden=true;$('error').textContent=e.message;return null;}finally{busy=false;$('refresh').disabled=false;}}
function show(text){$('report-panel').hidden=false;$('report').value=text;$('report').focus();$('report').select();}
async function generate(kind){if(dirty){$('error').textContent='補充欄位尚未儲存，請先儲存，再產生最新簡報資料。';return;}const s=await refresh();if(!s)return;const text=s.presentationText;if(kind==='preview'){show(text);return;}if(kind==='txt'){const url=URL.createObjectURL(new Blob(['\uFEFF',text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='足跡防護-簡報整理資料.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='已下載UTF-8簡報整理資料';return;}try{await navigator.clipboard.writeText(text);$('status').textContent='已複製簡報整理資料';}catch{show(text);$('status').textContent='瀏覽器拒絕自動複製，請在文字框全選後手動複製。';}}
$('refresh').onclick=refresh;$('copy').onclick=()=>generate('copy');$('preview').onclick=()=>generate('preview');$('txt').onclick=()=>generate('txt');$('csv').onclick=()=>{location.href='/api/admin/study/export';};
$('metadata').oninput=e=>{dirty=true;if(e.target.name!=='privacyReviewed')$('metadata').elements.namedItem('privacyReviewed').checked=false;$('save-status').textContent='尚未儲存；修改文字後請重新確認已去除個資。';};
$('add-feedback').onclick=()=>{if($('feedback-edit').children.length>=10)return;feedbackRow();dirty=true;$('metadata').elements.namedItem('privacyReviewed').checked=false;};
$('metadata').onsubmit=async e=>{e.preventDefault();if(!latest||busy)return;const form=e.target,content={};for(const key of ['testingDate','method','source','controlGroup','limitations','finding','evidence','completedChanges','plannedChanges'])content[key]=form.elements.namedItem(key).value;content.privacyReviewed=form.elements.namedItem('privacyReviewed').checked;content.feedback=[...$('feedback-edit').children].map(row=>({text:row.querySelector('.feedback-text').value,approved:row.querySelector('.feedback-approved').checked}));$('save').disabled=true;try{const response=await fetch('/api/admin/study/metadata',{method:'PUT',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:latest.metadata.revision,content})});if(!response.ok){const v=await response.json();throw Error(v.error||'儲存失敗');}dirty=false;await refresh();$('save-status').textContent='已儲存補充欄位';}catch(e){$('error').textContent=e.message;$('save').disabled=false;}};
$('delete-one').onclick=async()=>{const id=$('delete-id').value.trim();if(!/^[a-f0-9-]{36}$/.test(id)){ $('delete-status').textContent='請填入完整匿名編號。';return;}if(!confirm('確認已備份，並依受測者要求刪除這一筆研究紀錄？'))return;if(prompt('請輸入「刪除」確認，此動作無法復原。')!=='刪除')return;$('delete-one').disabled=true;try{const response=await fetch('/api/admin/study/session',{method:'DELETE',redirect:'error',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,confirm:'刪除此匿名紀錄'})});if(!response.ok)throw Error('刪除失敗，請確認登入狀態。');const result=await response.json();$('delete-status').textContent=result.deleted?'已刪除指定研究紀錄':'沒有找到該匿名紀錄';$('delete-id').value='';await refresh();}catch(e){$('error').textContent=e.message;$('delete-one').disabled=false;}};
refresh();
</script></body></html>`;
