// Isolated in-memory fixtures. Never write these records to remote D1.
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { banks, bankVersion, STUDY_VERSION, WEBSITE_VERSION, type Form } from '../research/banks.ts';
import { gradeTest, type StudyRow, type Step } from '../research/paired-core.ts';
export function answers(form:Form,recognition=4,protection=true){return Object.fromEntries(banks[form].map((q,i)=>[q.id,i===4?(protection?['1','2']:['1','4']):[q.options.find(o=>o.correct===(i<recognition))!.id]]));}
export function fixture(index:number,order:'AB'|'BA'='AB'):StudyRow{
 const pre=order[0] as Form,post=order[1] as Form,start=new Date(Date.UTC(2026,9,7,0,index)).toISOString(),end=new Date(Date.parse(start)+(index+1)*60000).toISOString();
 const step=(stage:Step['stage'],form:Form|null,input:unknown):Step=>({stage,form,bank_version:form?bankVersion(form):null,started_at:start,completed_at:end,answers_json:JSON.stringify(input),results_json:JSON.stringify(form?gradeTest(form,input):{completed:true})});
 return {id:crypto.randomUUID(),study_version:STUDY_VERSION,website_version:WEBSITE_VERSION,form_order:order,pre_version:bankVersion(pre),post_version:bankVersion(post),started_at:start,completed_at:end,stage:'done',steps:[step('pre',pre,answers(pre,2)),step('learning',null,{}),step('post',post,answers(post,3,index<10)),step('survey',null,{actions:index<9?['route']:['none'],assistance:index<10?(index<5?'none':'small'):'repeated',usability:4,problems:['none'],feedback:index===0?'姓名：王小明，示例高中，a.person@example.org，0912345678，@private_name。':''})]};
}
export function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');for(const name of ['0001_single_quiz.sql','0002_paired_study.sql'])sqlite.exec(readFileSync(new URL('../research/migrations/'+name,import.meta.url),'utf8'));
 const DB={prepare(sql:string){let args:unknown[]=[];const statement={bind(...values:unknown[]){args=values;return statement;},async first(){return sqlite.prepare(sql).get(...args as [])??null;},async all(){return {results:sqlite.prepare(sql).all(...args as [])};},async run(){if(/^\s*SELECT/i.test(sql))return {results:sqlite.prepare(sql).all(...args as [])};return {meta:{changes:Number(sqlite.prepare(sql).run(...args as []).changes)}};}};return statement;},async batch(statements:{run:()=>Promise<unknown>}[]){sqlite.exec('BEGIN');try{const results=[];for(const stmt of statements)results.push(await stmt.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {sqlite,DB:DB as unknown as D1Database};}
export function seed(sqlite:DatabaseSync,row:StudyRow){sqlite.prepare('INSERT INTO study_sessions(id,request_id,token_hash,consent,consent_version,study_version,website_version,form_order,pre_version,post_version,started_at,stage,stage_started_at,completed_at) VALUES(?,?,?,1,?,?,?,?,?,?,?,?,?,?)').run(row.id,crypto.randomUUID(),crypto.randomUUID(),'consent-v2',row.study_version,row.website_version,row.form_order,row.pre_version,row.post_version,row.started_at,row.stage,row.started_at,row.completed_at);
 for(const s of row.steps)sqlite.prepare('INSERT INTO study_steps(session_id,stage,form,bank_version,started_at,completed_at,answers_json,results_json) VALUES(?,?,?,?,?,?,?,?)').run(row.id,s.stage,s.form,s.bank_version,s.started_at,s.completed_at,s.answers_json,s.results_json);}
