import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import worker from '../research/worker.ts';
import {database} from './paired-fixtures.ts';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const {DB,sqlite}=database(),root=path.resolve('dist/client');
const server=createServer(async(req,res)=>{try{let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/footprint-unlink/,'');if(!pathname||pathname==='/')pathname='/index.html';const file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port,url=base+'/footprint-unlink/';
const env={DB,ALLOWED_ORIGIN:base,TEAM_DOMAIN:'https://test.cloudflareaccess.com',POLICY_AUD:'local',ADMIN_EMAILS:'admin@example.org',RETENTION_DAYS:'90',STUDY_ENABLED:'true'};
let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:1100,height:900}});let calls=0,starts=0,failFirstStart=true;
 await page.route('https://footprint-research.footprint-unlink-11430106.workers.dev/api/**',async route=>{calls++;const original=route.request(),headers=new Headers(original.headers());headers.set('Origin',base);const response=await worker.fetch(new Request(original.url(),{method:original.method(),headers,...(original.postData()?{body:original.postData()}:{})}),env);if(original.url().endsWith('/start')){starts++;if(failFirstStart){failFirstStart=false;await route.fulfill({status:503,json:{error:'模擬已建立但回應中斷'}});return;}}await route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:await response.text()});});
 await page.goto(url);await page.getByRole('button',{name:'開始體驗',exact:true}).waitFor();assert.equal(calls,0);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_sessions').get().n,0);
 await page.goto(url+'?research=1');const begin=page.getByRole('button',{name:'同意並開始前測',exact:true}),agree=page.getByRole('checkbox',{name:'我已閱讀並同意參加匿名研究測試。'});await begin.waitFor();assert.equal(await begin.isDisabled(),true);assert.equal(starts,0);await agree.check();await agree.uncheck();assert.equal(await begin.isDisabled(),true);assert.equal(starts,0);
 await page.getByRole('link',{name:'返回一般體驗',exact:true}).click();await page.getByRole('button',{name:'開始體驗',exact:true}).waitFor();assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_sessions').get().n,0);
 await page.goto(url+'?research=1');await agree.check();await begin.click();await page.getByRole('alert').filter({hasText:'模擬已建立'}).waitFor();await page.getByRole('button',{name:'重新連線／續填',exact:true}).click();await page.getByRole('heading',{name:'前測',exact:true}).waitFor();assert.equal(starts,2);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_sessions').get().n,1);
 await page.locator('fieldset').first().getByRole('radio').first().check();await page.reload();await page.getByRole('heading',{name:'前測',exact:true}).waitFor();assert.equal(await page.locator('fieldset').first().getByRole('radio').first().isChecked(),true);
 for(let i=0;i<4;i++)await page.locator('fieldset').nth(i).getByRole('radio').first().check();for(let i=0;i<2;i++)await page.locator('fieldset').nth(4).getByRole('checkbox').nth(i).check();await page.getByRole('button',{name:'完成前測，進入學習',exact:true}).click();await page.getByRole('button',{name:'開始體驗',exact:true}).waitFor();assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_steps').get().n,1);
 await page.getByRole('button',{name:'開始體驗',exact:true}).click();await page.getByRole('button',{name:'開始辨識',exact:true}).click();const questions=JSON.parse(await readFile('data/questions.json','utf8'));
 for(const q of questions){for(const o of q.options.filter(o=>o.correct))await page.getByRole(q.type==='single'?'radio':'checkbox').nth(q.options.indexOf(o)).click();await page.getByRole('button',{name:'確認答案',exact:true}).click();await page.getByRole('button',{name:/^(下一題|進入第二階段：防護|進入第三階段：回查|第四階段：回到自己)$/}).click();}
 await page.getByRole('checkbox',{name:'以上皆無',exact:true}).click();await page.getByRole('button',{name:'查看結果與我的回查建議',exact:true}).click();await page.getByRole('button',{name:'完成學習，進入後測',exact:true}).click();await page.getByRole('heading',{name:'後測',exact:true}).waitFor();
 for(let i=0;i<4;i++)await page.locator('fieldset').nth(i).getByRole('radio').first().check();for(let i=0;i<2;i++)await page.locator('fieldset').nth(4).getByRole('checkbox').nth(i).check();await page.getByRole('button',{name:'完成後測，填寫問卷',exact:true}).click();await page.getByRole('heading',{name:'結束問卷',exact:true}).waitFor();
 const routeAction=page.getByRole('checkbox',{name:'調整路線、起終點的公開範圍',exact:true}),noneAction=page.getByRole('checkbox',{name:'暫不採取行動',exact:true});await routeAction.check();await noneAction.check();assert.equal(await routeAction.isChecked(),false);await routeAction.check();assert.equal(await noneAction.isChecked(),false);await page.getByRole('radio',{name:'不需協助',exact:true}).check();await page.getByRole('combobox').selectOption('4');await page.getByRole('checkbox',{name:'沒有遇到問題',exact:true}).check();await page.getByRole('button',{name:'完成研究測試',exact:true}).click();await page.getByRole('heading',{name:'研究測試已完成',exact:true}).waitFor();assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_sessions').get().n,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_steps').get().n,4);
 await page.reload();await page.getByRole('heading',{name:'研究測試已完成',exact:true}).waitFor();assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM study_sessions').get().n,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM sessions').get().n,0);
 await page.getByRole('button',{name:'下一位受測者',exact:true}).click();await begin.waitFor();assert.equal(await begin.isDisabled(),true);assert.equal(await agree.isChecked(),false);
 env.STUDY_ENABLED='false';await page.reload();await page.getByText('A/B題庫仍待團隊確認，正式研究入口尚未開放。',{exact:true}).waitFor();await agree.check();assert.equal(await begin.isDisabled(),true);await mkdir('outputs',{recursive:true});await page.screenshot({path:'outputs/research-closed-test.png',fullPage:true});
 console.log('PASS: 一般訪客零API、未同意零紀錄、同意可取消、返回體驗、開始回應中斷重送仍1人、刷新續填、前測→8題學習／回查→不同後測→互斥問卷→完成、下一位重新同意、題庫未核准禁止開始。僅本機隔離資料庫。');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));sqlite.close();}
