CREATE TABLE IF NOT EXISTS sessions (
 id TEXT PRIMARY KEY,
 token_hash TEXT NOT NULL UNIQUE,
 consent INTEGER NOT NULL CHECK(consent=1),
 order_code TEXT NOT NULL CHECK(order_code IN ('AB','BA')),
 started_at TEXT NOT NULL,
 pre_started_at TEXT,
 pre_completed_at TEXT,
 experience_started_at TEXT,
 experience_completed_at TEXT,
 post_started_at TEXT,
 post_completed_at TEXT,
 completed_at TEXT,
 pre_bank_version TEXT NOT NULL,
 post_bank_version TEXT NOT NULL,
 pre_answers TEXT,
 post_answers TEXT,
 pre_item_results TEXT,
 post_item_results TEXT,
 pre_score INTEGER CHECK(pre_score BETWEEN 0 AND 100),
 post_score INTEGER CHECK(post_score BETWEEN 0 AND 100),
 post_protection INTEGER CHECK(post_protection IN (0,1)),
 survey TEXT
);
CREATE INDEX IF NOT EXISTS sessions_started ON sessions(started_at);
